name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [16, 18, 20]

    steps:
      - uses: actions/setup-node@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          # node-version: ${{ matrix.node }}
          node-version: 20
      - run: yarn
      - run: yarn run test

      - name: Generate Tag
        id: generate_tag
        run: | 
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build docker image
        run: docker build -t lucamoraees/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }} .
        
      - name: Push image
        run: docker push -t lucamoraees/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }}